version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: barter
      POSTGRES_USER: barter
      POSTGRES_PASSWORD: barter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: barter
      DB_USER: barter
      DB_PASSWORD: barter
      DB_HOST: db
      DB_PORT: 5432
      DB_SCHEMA: barter_system
    depends_on:
      - db

volumes:
  postgres_data: